project:
  type: website

website:
  title: "Student Sense of Community in Quantitative Sciences (SOCQS)"
  navbar:
    background: primary
    right:
      - href: index.qmd
        text: Home
      - href: ecots22-slides.qmd
        text: "eCOTS 2022 slides"
      - href: focus-groups
        text: "Focus group themes"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



