project:
  type: website
  output-dir: docs

website:
  title: "SOCQS"
  navbar:
    background: primary
    right:
      - href: team
        text: "Meet the team"
      - href: ecots22-slides.qmd
        text: "eCOTS 2022 slides"
      - href: focus-groups
        text: "Pilot focus groups"

format:
  html:
    theme: [cosmo, styles.scss]
    toc: true
    code-copy: true
    code-overflow: wrap



