---
title: "Student Sense of Community in Quantitative Sciences (SOCQS)"
---

To increase diversity and representation in math and statistics and in STEM at large, it is essential that undergraduate students be able to envision themselves as contributing members of these fields. Students' sense of belonging is a critical factor in their persistence, and more broadly their sense of community is correlated with academic motivation and perceived learning. 

The SOCQS project, begun in Fall 2020, is a mixed-methods investigation of classroom community in introductory undergraduate mathematics and statistics courses. It is crucial to understand the student experience in this setting, as it is there that many students first assess whether they can successfully pursue a particular STEM major or career. The project's goals are threefold:

1.  To identify pedagogies, policies, and structures in introductory quantitative science courses which correlate with an increased sense of classroom community;  

2.  To better understand how students in introductory quantitative science courses perceive and experience classroom community; and  

3.  To analyze how these perceptions and experiences differ across a diverse population, including along demographic axes and different learning modalities and preferences. 

------------------------------------------------------------------------

This project is funded by the [Carry the Innovation Forward Grant](https://learninginnovation.duke.edu/carry-the-innovation-forward/) from [Duke Learning Innovation](https://learninginnovation.duke.edu/).
